/*
Create a function `getLastColor` that:

- Takes a string row, representing the first row of a triangle. 
Each character in the `row` is one of the colors: `R`, `G`, 
or `B`.
- Returns the final color at the base of the triangle.

Here's how to arrive at the final color:

- Each successive row is generated by examining pairs of 
  adjacent colors from the previous row.
- If two adjacent colors are the same, the new row gets that 
  same color, e.g. `G G -> G`.
- If they are different, the missing color is used in the 
  new row, e.g. `B G -> R`.
- The process continues until there's only one color left 
  in the last row.

Graphic representation:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
*/

// Refactored
function returnLetter(currentEl, nextEl) {
  if (currentEl === nextEl) {
    return currentEl;
  }

  if ((currentEl === 'R' && nextEl === 'B')
      || (currentEl === 'B' && nextEl === 'R')
  ) {
    return 'G';
  }

  if ((currentEl === 'G' && nextEl === 'B')
      || (currentEl === 'B' && nextEl === 'G')
  ) {
    return 'R';
  }
    
  return 'B';
}

function getLastColor(row) {
  if (row.length === 1) {
    return row;
  }

  let currentRow = row;
  let nextRow = '';

  for (let idx1 = 0; currentRow.length !== 1; idx1++) {
    for (let idx2 = 0; idx2 < currentRow.length - 1; idx2++) {
      const currentEl = currentRow[idx2];
      const nextEl = currentRow[idx2 + 1];
      const letter = returnLetter(currentEl, nextEl);
      
      nextRow += letter;
    }
    currentRow = nextRow;
    nextRow = '';
  }

  return currentRow;
}

console.log(getLastColor('BR')); // 'G'
console.log(getLastColor('RRR')); // 'R'
console.log(getLastColor('RBRGBRB')); // 'G'
console.log(getLastColor('B')); // 'B'
console.log(getLastColor('RGB')); // 'G'

// Works as expected



// // Solution (build the whole row
// function getLastColor(row) {
//   if (row.length === 1) {
//     return row;
//   }

//   let currentRow = row;
//   let nextRow = [];

//   for (let idx1 = 0; currentRow.length !== 1; idx1++) {
//     for (let idx2 = 0; idx2 < currentRow.length; idx2++) {
//       const currentEl = currentRow[idx2];
//       const nextEl = currentRow[idx2 + 1];

//       if (currentEl === nextEl) {
//         nextRow.push(currentEl);
//       }
    
//       if ((currentEl === 'R' && nextEl === 'B')
//           || (currentEl === 'B' && nextEl === 'R')
//       ) {
//         nextRow.push('G');
//       }
    
//       if ((currentEl === 'G' && nextEl === 'B')
//           || (currentEl === 'B' && nextEl === 'G')
//       ) {
//         nextRow.push('R');
//       }

//       if ((currentEl === 'G' && nextEl === 'R')
//           || (currentEl === 'R' && nextEl === 'G')
//       ) {
//         nextRow.push('B');
//       }
//     }
//     currentRow = nextRow;
//     nextRow = [];
//   }

//   return currentRow.join('');
// }

// console.log(getLastColor('BR')); // 'G'
// console.log(getLastColor('RRR')); // 'R'
// console.log(getLastColor('RBRGBRB')); // 'G'
// console.log(getLastColor('B')); // 'B'

// // `should work for an input of three characters with 
// // different colors`
// console.log(getLastColor('RGB')); // 'G'

// // Works as expected





// // Experiments (find color of last pairs of the next row):
// function getLastColor(row) {
//   if (row.length === 1) {
//     return row;
//   }

//   const last = row[row.length - 1];
//   const previous = row[row.length - 2];

//   if (last === previous) {
//     return last;
//   }

//   if ((last === 'R' && previous === 'B')
//       || (last === 'B' && previous === 'R')
//   ) {
//     return 'G';
//   }

//   if ((last === 'G' && previous === 'B')
//       || (last === 'B' && previous === 'G')
//   ) {
//     return 'R';
//   }

//   return 'B';
// }

// console.log(getLastColor('BR')); // 'G'
// console.log(getLastColor('RRR')); // 'R'
// console.log(getLastColor('RBRGBRB')); // 'G'
// console.log(getLastColor('B')); // 'B'




// // Doesn't work with `switch/ case`
// function getLastColor(row) {
//   if (row.length === 1) {
//     return row;
//   }

//   const last = row[row.length - 1];
//   const previous = row[row.length - 2];
  
//   switch (last) {
//     case previous:
//       return last;
//     case 'R' && previous === 'B': // false
//     case 'B' && previous === 'R': // true
//       return 'G'; // isn't executed because of false
//     default:
//       return 'B';
//   }
// }

// console.log(getLastColor('BR')); // 'G'
// console.log(getLastColor('RRR')); // 'R'
// // console.log(getLastColor('RBRGBRB')); // 'G' // false
// console.log(getLastColor('B')); // 'B'
