/*
Create a function `getLastColor` that:

- Takes a string row, representing the first row of a triangle. 
Each character in the `row` is one of the colors: `R`, `G`, 
or `B`.
- Returns the final color at the base of the triangle.

Here's how to arrive at the final color:

- Each successive row is generated by examining pairs of 
  adjacent colors from the previous row.
- If two adjacent colors are the same, the new row gets that 
  same color, e.g. `G G -> G`.
- If they are different, the missing color is used in the 
  new row, e.g. `B G -> R`.
- The process continues until there's only one color left 
  in the last row.

Graphic representation:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
*/

// Solution
function getLastColor(row) {
  if (row.length === 1) {
    return row;
  }

  const last = row[row.length - 1];
  const previous = row[row.length - 2];
  
  if (last === previous) {
    return last;
  }

  if ((last === 'R' && previous === 'B')
      || (last === 'B' && previous === 'R')
  ) {
    return 'G';
  }

  return 'B';
}

console.log(getLastColor('BR')); // 'G'
console.log(getLastColor('RRR')); // 'R'
console.log(getLastColor('RBRGBRB')); // 'G'
console.log(getLastColor('B')); // 'B'



// Experiments:
// Doesn't work with `switch/ case`
function getLastColor(row) {
  if (row.length === 1) {
    return row;
  }

  const last = row[row.length - 1];
  const previous = row[row.length - 2];
  
  switch (last) {
    case previous:
      return last;
    case 'R' && previous === 'B': // false
    case 'B' && previous === 'R': // true
      return 'G'; // isn't executed because of false
    default:
      return 'B';
  }
}

console.log(getLastColor('BR')); // 'G'
console.log(getLastColor('RRR')); // 'R'
// console.log(getLastColor('RBRGBRB')); // 'G' // false
console.log(getLastColor('B')); // 'B'
